# Currently disabled to fix later need to install libgl-dev and maybe other dependencies.

name:  'Linux'
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Update the default profile with compiler settings.
      - name: Configure Conan
        run: |
          conan config set general.default_package_id_mode=full_version_mode
          conan profile new default --detect
          conan profile update settings.compiler=gcc default
          conan profile update settings.compiler.version=9 default
          conan profile update settings.compiler.cppstd=20 default

      # Just build all dependencies on every build.
      - name: Install Dependencies
        run: |
          mkdir build && cd build
          conan install .. -s build_type=Release --build=missing

      - name: Configure
        working-directory: build
        run: conan build .. -c
      
      - name: Build
        working-directory: build
        run: conan build ..

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: build-artifacts
          path: build
